# The `eddieob/min-gpt:3` was minted using this dockerfile
FROM --platform=linux/amd64 pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
RUN pip install torch torchvision fsspec hydra-core omegaconf aiohttp requests matplotlib
